---
abstract: 'Convert Strings to English Program Identifiers'
author:
  - 'Rafael Kitover, C<< <rkitover@cpan.org> >>'
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-ToIdentifier-EN
no_index:
  directory:
    - inc
    - t
provides:
  String::ToIdentifier::EN:
    file: lib/String/ToIdentifier/EN.pm
    version: 0.08
  String::ToIdentifier::EN::Unicode:
    file: lib/String/ToIdentifier/EN/Unicode.pm
requires:
  Exporter: 5.57
  Lingua::EN::Inflect::Phrase: 0.14
  Text::Unidecode: 0.04
  namespace::clean: 0.20
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/string-toidentifier-en.git
version: 0.08
