---
abstract: 'Convert Strings to English Program Identifiers'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-ToIdentifier-EN
no_index:
  directory:
    - t
requires:
  Exporter: 0
  Lingua::EN::Inflect::Phrase: 0
  Text::Unidecode: 0
  Unicode::UCD: 0
  base: 0
  namespace::clean: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=String-ToIdentifier-EN
  homepage: http://metacpan.org/release/String-ToIdentifier-EN
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/string-toidentifier-en.git
version: 0.10
x_authority: cpan:RKITOVER
